"""Add forecast and daily forecast tables

Revision ID: fbef48a236e0
Revises: d8dddabb2a85
Create Date: 2025-08-20 23:43:34.401705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbef48a236e0'
down_revision: Union[str, Sequence[str], None] = 'd8dddabb2a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('forecast_days', sa.Integer(), nullable=False, server_default='5'),
    sa.Column('request_time', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('is_cached', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('is_mock', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('cache_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_data', sa.JSON(), nullable=False),
    sa.Column('avg_temperature', sa.Float(), nullable=True),
    sa.Column('min_temperature', sa.Float(), nullable=True),
    sa.Column('max_temperature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_requests_city'), 'forecast_requests', ['city'], unique=False)
    op.create_index(op.f('ix_forecast_requests_id'), 'forecast_requests', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_requests_request_time'), 'forecast_requests', ['request_time'], unique=False)
    op.create_index(op.f('ix_forecast_requests_user_id'), 'forecast_requests', ['user_id'], unique=False)
    op.create_table('weather_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feels_like', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('request_time', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('is_mock', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_requests_city'), 'weather_requests', ['city'], unique=False)
    op.create_index(op.f('ix_weather_requests_id'), 'weather_requests', ['id'], unique=False)
    op.create_index(op.f('ix_weather_requests_user_id'), 'weather_requests', ['user_id'], unique=False)
    op.create_table('daily_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_request_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=False),
    sa.Column('temperature_avg', sa.Float(), nullable=True),
    sa.Column('feels_like_min', sa.Float(), nullable=True),
    sa.Column('feels_like_max', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('icon_code', sa.String(length=10), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('precipitation_probability', sa.Integer(), nullable=True),
    sa.Column('precipitation_amount', sa.Float(), nullable=True),
    sa.Column('sunrise_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daylight_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_request_id'], ['forecast_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_forecasts_forecast_date'), 'daily_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_daily_forecasts_forecast_request_id'), 'daily_forecasts', ['forecast_request_id'], unique=False)
    op.create_index(op.f('ix_daily_forecasts_id'), 'daily_forecasts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_forecasts_id'), table_name='daily_forecasts')
    op.drop_index(op.f('ix_daily_forecasts_forecast_request_id'), table_name='daily_forecasts')
    op.drop_index(op.f('ix_daily_forecasts_forecast_date'), table_name='daily_forecasts')
    op.drop_table('daily_forecasts')
    op.drop_index(op.f('ix_weather_requests_user_id'), table_name='weather_requests')
    op.drop_index(op.f('ix_weather_requests_id'), table_name='weather_requests')
    op.drop_index(op.f('ix_weather_requests_city'), table_name='weather_requests')
    op.drop_table('weather_requests')
    op.drop_index(op.f('ix_forecast_requests_user_id'), table_name='forecast_requests')
    op.drop_index(op.f('ix_forecast_requests_request_time'), table_name='forecast_requests')
    op.drop_index(op.f('ix_forecast_requests_id'), table_name='forecast_requests')
    op.drop_index(op.f('ix_forecast_requests_city'), table_name='forecast_requests')
    op.drop_table('forecast_requests')
    # ### end Alembic commands ###
